# Generated by Django 5.0.5 on 2024-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_color',
            name='session_key',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterModelTable(
            name='main_color',
            table='session_palette',
        ),
    ]
