# Generated by Django 5.0.5 on 2024-09-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_main_color_session_key_alter_main_color_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_color',
            name='web_palette',
        ),
        migrations.AddField(
            model_name='main_color',
            name='session_palette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.theme_train'),
        ),
    ]
